# SITE CONFIGURATION
baseurl: "/"
url: "https://hnap.de"

# THEME-SPECIFIC CONFIGURATION
title: HAMNET Access Protocol # site's title
description: "HAMNET Access Protocol" # used by search engines
avatar: assets/img/hnap_logo_quadrat.png
favicon: assets/favicon.ico

# Header and footer text
header_text: "HAMNET Access Protocol"
header_feature_image: assets/img/main.png
footer_text:
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> and <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex:                                                  # Enable if using math markup
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
disqus_shortname:                                       # Your discus shortname for comments
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml 
  
# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-multiple-languages-plugin]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github

# Colours, typography and padding
# Open the "_sass > base" folder, and open "_variables.scss"

languages: ["en"]
exclude_from_localizations: ["assets", "CNAME", "gh-pages-deploy.sh"]

